swagger: '2.0'
info:
  description: Delli API sample
  version: 1.0.0
  title: Delli Api
schemes:
  - https
produces:
  - application/json
paths:
  /api/v1/auth/register:
    post:
      tags:
        - authentication-controller
      operationId: register
      x-google-backend:
        address: https://security-ffsfpsk5dq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK

  /api/v1/auth/authenticate:
    post:
      tags:
        - authentication-controller
      operationId: authenticate
      x-google-backend:
        address: https://security-ffsfpsk5dq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "200":
          description: OK

  /api/predict:
    post:
      tags:
        - DiseaseView
      operationId: predict
      x-google-backend:
        address: https://derma-ffsfpsk5dq-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        "201":
          description: OK
        "400":
          description: REQUEST FORM DATA

